### ISSUE TITLE
Add GCS to all pages

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/land-records#40]

**Comment by ThomasThoren** [comment]
Actually, this isn't so simple for GCS. We don't want users to see GCS for every page, but we also might want users who are linked directly to a sub-page to see GCS. @myersnews, should I only turn it on for the homepage (just the search input, no map)?

**Comment by myersnews** [comment]
We could tackle this a number of ways. For now just the opening search page is fine. 
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
