### ISSUE TITLE
Various text revisions

### ISSUE THREAD

**Issue by myersnews** [TheLens/land-records#58]
Text for advanced search on main page:
*NEW* (it's italicizing b/c of markdown here; ignore that) Advanced search by neighborhood and ZIP code

Single sale page
Revise the not-found assessor note to say:
Could not find this property on the Orleans Parish Assessor's Office site.

"from" note above search bar
Revise to say "Our data" not "The source of our data"

About note
Revise to say:
*Properties with an asterisk are not mapped because their locations have not been verified.

**Comment by ThomasThoren** [comment]
Do you want to remove the link to the assessor's search page in the not found note?

**Comment by myersnews** [comment]
no, keep it.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
