### ISSUE TITLE
ZIP code search not working in text window

### ISSUE THREAD

**Issue by myersnews** [TheLens/land-records#60]
Currently returns no results when you type a ZIP in the text bar.

Even though we have the ZIP search I think it should still allow searching in the text bar.

Let me know if you disagree.

**Comment by ThomasThoren** [comment]
You're right. The search bar displays neighborhood suggestions right now, but that feature was actually removed so it doesn't work either.

I'll add zips and neighborhoods to the search bar, along with autocomplete suggestions.
