### ISSUE TITLE
Autosuggest very slow on iPhone

### ISSUE THREAD

**Issue by myersnews** [TheLens/land-records#65]
this looks like it's been resolved but i'm noting it here so we can keep an eye on it.

**Comment by ThomasThoren** [comment]
Leaving this until I can test on phone. It should be much faster now though.

**Comment by ThomasThoren** [comment]
Works fine for me while on our wireless network.

**Comment by myersnews** [comment]
I didn’t check on LTE actually. We should.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
