### ISSUE TITLE
Tooltips sometimes cover dots on map

### ISSUE THREAD

**Issue by myersnews** [TheLens/land-records#66]
Unlikely people will click on them if they can't see them.

**Comment by ThomasThoren** [comment]
The dot you are currently hovering over or other dots on the map?

**Comment by myersnews** [comment]
The one I’m hovering on.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Hmm, I'll bump up the offset dimensions to make sure this doesn't happen.
