### ISSUE TITLE
Autosuggest: search immediately after selecting

### ISSUE THREAD

**Issue by myersnews** [TheLens/land-records#67]
Same on desktop and phone: When you select an autosuggest item, it puts that text in the search bar. You have to touch/click again to search. Unintuitive in my opinion. 

Google searches automatically when you choose one and I think that's what we should do.

**Comment by ThomasThoren** [comment]
It used to work like this, so it must be some new bug.

**Comment by ThomasThoren** [comment]
This works correctly for me. Were you clicking on a neighborhood? They weren't even supposed to be visible, so they wouldn't have loaded correctly.

**Comment by myersnews** [comment]
i was clicking on whatever came up first on autosuggest.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
That would have been a neighborhood probably. I'll add zips and make sure the neighborhoods are working correctly, then have you try it again.

**Comment by ThomasThoren** [comment]
Should be better now. I deliberately made it so you can only search by neighborhood or zip code in the search bar if select them in the autocomplete dropdown menu. It's too difficult to let users type in "70125" and get a zip code search back, but type in "7012" and expect an address search back. Or what if an address has "70125" in it? The only surefire way of knowing what the user wants is if they select the zip/neighborhood under its heading in the dropdown.

**Comment by myersnews** [comment]
iPhone: typed "park" and clicked on suggest option "pontchartrain park." didn't fill in text bar. touched it again. nothing happens.

typed "heff." selected sheffield st address. filled the text bar, but didn't search. when i hit search, it doesn't do anything.

**Comment by ThomasThoren** [comment]
It shouldn't fill in the text bar with either a neighborhood or zip code. That should opened the advanced search area and display those in their respective dropdown menus.

**Comment by myersnews** [comment]
oh, i see. but those things aren't visible on the screen. so it looks like nothing is happening.

the reason that sheffield wasn't working is that it had selected the pontchartrain park neighborhood and was looking for that address in that neighborhood.

the sheffield search works when i cleared the neighborhood menu. but the results appear below the advanced search options, off the screen, so i can't tell that it did anything. 

i think we have to deal with the usability issues from the combinations of advanced search, autosuggest that pulls something from a dropdown, and mobile. i don't think any user will figure out that if they choose an autosuggest from the options on the text bar, that it will select something on a dropdown below.

**Comment by ThomasThoren** [comment]
This is partially why I didn't have the option to search zip or neighborhood through the text bar. It's nice to have the extra search option, but it's also confusing because this lets users search two different ways (keywords and geographic areas). It sends a neighborhood search to the dropdown in the advanced search because it needs to differentiate which of those search types it is (Is "Carrollton" a search for addresses on that street, or the neighborhood?)

I'm not sure what the answer is for the phone view. It's almost impossible to pack all of these options we want to show into a single viewport. Would auto scrolling down to the map do the trick?
