### ISSUE TITLE
2 search buttons appear on advanced search 

### ISSUE THREAD

**Issue by myersnews** [TheLens/land-records#76]

**Comment by ThomasThoren** [comment]
Probably only on the initial page though, right? I made the second button only appear in the advance search area dropdown. That initial page already has a second button though, which would explain why two appear.

**Comment by myersnews** [comment]
right, on the initial page. there are 2 buttons stacked on top of each other, in addition to the one at the top.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
