### ISSUE TITLE
Deal with tooltips that require scrolling

### ISSUE THREAD

**Issue by myersnews** [TheLens/land-records#77]
When you move off the marker to scroll, the tooltip disappears.

![screenshot 2015-02-12 12 29 26](https://cloud.githubusercontent.com/assets/413882/6174196/dda12286-b2b2-11e4-94e3-94fba32877e2.png)

**Comment by ThomasThoren** [comment]
Rather than that, the tooltip should not try to display everything for massive sales like this. It should cut off each field after X characters, append with "..." and let users read on at the sale's individual page. The tooltip isn't meant to handle this much information.

**Comment by myersnews** [comment]
good solution.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
