### ISSUE TITLE
why doesn't this map?

### ISSUE THREAD

**Issue by myersnews** [TheLens/land-records#78]
http://162.243.152.217:5004/realestate/search?q=Kenneth%20E.%20Whichard

**Comment by ThomasThoren** [comment]
PostGIS' geocoder didn't find it for one reason or another. It's not as good as a paid geocoder like Google, so we'll always have some of these that will require dashboard editing.

**Comment by ThomasThoren** [comment]
Going to close this now since there isn't much to be done with the current geocoding setup. We will have to catch this in the manual review. Google's geocoder might help, too. See #99.
