### ISSUE TITLE
"what does this mean" link above column is missing

### ISSUE THREAD

**Issue by myersnews** [TheLens/land-records#80]

**Comment by ThomasThoren** [comment]
I took this out because it didn't seem necessary anymore. #53

**Comment by ThomasThoren** [comment]
Instrument numbers are gone, so I don't think we need this anymore since the rest of the columns are self-explanatory. Thoughts @myersnews and @AbeHandler?

**Comment by myersnews** [comment]
Right, makes sense. But it should go on the single-sale page instead.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
