### ISSUE TITLE
Phone design issues

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/land-records#83]
-No X in search input
-Tapping search and typing leaves page zoomed in
-In autocomplete menu, have to tap selection twice in order to initiate search
-After selecting autocomplete option, keyboard menu remains open.

**Comment by ThomasThoren** [comment]
Dropdown selection styles, too

**Comment by ThomasThoren** [comment]
-In autocomplete menu, have to tap selection twice in order to initiate search.
This is still an open issue, though this actually seems to be helpful more than it is a bug. This lets users tap their selection, verify they tapped the correct selection in the dropdown by observing the highlighted selection and then give the go-ahead to search for that option.

All other issues here are taken care of.

**Comment by myersnews** [comment]
That’s fine.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
