### ISSUE TITLE
Fix capitalization on X results found for Y above map

### ISSUE THREAD

**Issue by myersnews** [TheLens/land-records#85]
Hey Tom, I don't know what populates this, my search or the list of neighborhoods, but the note above the map says: 70 sales found in carrollton

Can we capitalize that and all neighborhood names?

**Comment by myersnews** [comment]
Can we also make the verb agree with subject for cases with one sale?

**Comment by ThomasThoren** [comment]
Any keywords are kept in the case they were entered. Neighborhoods should always be capitalized, so I'll fix that. I must have broken the verb tenses with these new changes, so I'll fix that as well.

**Comment by myersnews** [comment]
Sounds good.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
