### ISSUE TITLE
Search is confusing

### ISSUE THREAD

**Issue by AbeHandler** [TheLens/land-records#89]
If I type bywater it finds keyword="bywater" 

If I type bywater and wait for the neighborhoods dropdown and pick bywater, I see bywater. 

The "results text" needs to reflect that. The user should see how the computer is interpreting its request. 

"Visibility of system status
The system should always keep users informed about what is going on, through appropriate feedback within reasonable time."
http://www.nngroup.com/articles/ten-usability-heuristics/

**Comment by ThomasThoren** [comment]
Fixed the results language. Adding geographic borders to neighborhood and ZIP searches (see #91) will also help to reinforce which type of search the user performed.
