### ISSUE TITLE
Strange behavior on map move

### ISSUE THREAD

**Issue by AbeHandler** [TheLens/land-records#90]
Search for "neighborhood:leonidas". Map shows ~10 results. Then click "redo search on map move". Move away from that neighborhood. Properties disappear on map. that seems right. however, move back to leonidas. The properties in leonidas are gone except for two.

**Comment by ThomasThoren** [comment]
Good catch. This revealed an even bigger problem in the search logic. It only shows 2 sales when you go back because it is then using "Leonidas" as a keyword, not as a neighborhood area. Working on this now.

**Comment by ThomasThoren** [comment]
Should be better. Give it a whirl and let me know if you still see any problems.

**Comment by ThomasThoren** [comment]
Also added "...in the current map view" if the map view filter is turned on.
