### ISSUE TITLE
Draw geographic borders on map when searching by neighborhood or ZIP

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/land-records#91]

**Comment by AbeHandler** [comment]
this is a good idea.

**Comment by ThomasThoren** [comment]
Still working out a few kinks, but it's mostly done.

![screen shot 2015-02-22 at 2 54 10 am](https://cloud.githubusercontent.com/assets/5692185/6318013/2c0e21f2-ba3e-11e4-9eb4-5a49a6026806.png)
