### ISSUE TITLE
Test out Google geocoding service

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/land-records#99]
We would fall within the free daily limits, so it might be worth the time to switch over. Depends on whether it's an improvement or not. This could potentially catch seemingly simple addresses like in #78, which trip up the PostGIS geocoder.

https://developers.google.com/maps/documentation/geocoding/#Limits

**Comment by myersnews** [comment]
Put it to NICAR-L and see what people say.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Mar 2, 2015, at 11:06 AM, Thomas Thoren <notifications@github.com> wrote:

We would fall within the free daily limits, so it might be worth the time
to switch over. Depends on whether it's an improvement or not. This could
potentially catch seemingly simple addresses like in #78
<https://github.com/TheLens/land-records/issues/78>, which trip up the
PostGIS geocoder.

https://developers.google.com/maps/documentation/geocoding/#Limits

—
Reply to this email directly or view it on GitHub
<https://github.com/TheLens/land-records/issues/99>.
